---
- hosts: all
  become: yes

  vars:
    ansible_ssh_pipelining: 1

  vars_files:
    - vars.yml

  tasks:
  - name: Upgrade all packages
    raw: /usr/bin/dnf -y upgrade --refresh

  - name: Reboot system
    raw: /usr/sbin/reboot